spring.application.name=Language

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
spring.messages.cache-duration=0

# Thymeleaf 캐시 비활성화
spring.thymeleaf.cache=false

# 로깅 레벨 설정 (디버깅용)
logging.level.org.springframework.web.servlet.i18n=DEBUG
logging.level.com.language.config=DEBUG